-- Migration: Add missing transaction_type enum values

ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'DONATION';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'EXCHANGE';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'BUILT_TO_SUIT';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'SURFACE_RIGHT';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'RURAL_LEASE';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'GUARANTEES';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'FIDUCIARY';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'CAPITAL';
